function y = mOutFcn(in1,in2)
%mOutFcn
%    Y = mOutFcn(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    13-Jun-2023 18:36:36

phi_t = in1(4,:);
phi_dot_t = in1(10,:);
psi_t = in1(6,:);
psi_dot_t = in1(12,:);
theta_t = in1(5,:);
theta_dot_t = in1(11,:);
x_dot_t = in1(7,:);
x_t = in1(1,:);
y_dot_t = in1(8,:);
y_t = in1(2,:);
z_dot_t = in1(9,:);
z_t = in1(3,:);
y = [x_t;y_t;z_t;phi_t;theta_t;psi_t;x_dot_t;y_dot_t;z_dot_t;phi_dot_t;theta_dot_t;psi_dot_t];
